### ISSUE TITLE
How to filter PAS with low counts?

### ISSUE THREAD

**Issue by CTLife** [christear/APAIQ_release#6]
How many raw reads are required to support a reliable PAS?  Which parameter? 
We should discard it, if it is supported by only several reads (number of raw reads, but not the score of the PAS).

The input is bedgraph, but not BAM. So, we cannot know the number of raw reads?

Thanks.

**Comment by christear** [comment]
Please keep in mind, the read number from RNA-seq to support a PAS is not meaningful as (1) it will be impacted by the sequencing depth, (2) only the drop of coverage rather than the number of supporting read, might be able to indicate the PAS. In exonic region, read number is aways very high but there is no PAS at all. APAIQ only do the filtering at the beginning by requiring average RPM (RPM) at the upstream of each position higher than 0.05 (default). If you really would like to filter the PAS based on expression, you should run our regression model to quantify the expression of each PAS firstly and then do the filtering.
